vim.opt.relativenumber = true
vim.opt.number = true
vim.opt.wrap = false
vim.opt.clipboard = ""
vim.opt.conceallevel = 3 -- Show quote in json file or links in markdown
vim.opt.shiftwidth = 4
vim.opt.tabstop = 4
vim.opt.foldmethod = "indent"
vim.opt.foldlevelstart = 20
vim.opt.iskeyword = vim.opt.iskeyword + "-"
vim.opt.linebreak = true
vim.opt.undolevels = 1000
vim.opt.sessionoptions = { "buffers", "curdir", "tabpages", "winsize", "help", "globals", "skiprtp", "folds" }
vim.opt.splitright = true
vim.opt.cmdheight = 0
