#+TITLE: PERSONAL TODO
#+AUTHOR: Chop Tr (trchopan)

* Note:

+ Keychron K2 V2
   https://techzones.vn/keychron-k2-v2-led-rgb-gateron-brown-hotswap-phien-ban-nhom


* Checkout NewsAPI

Looks like a good source of information

I have idea of morning checking and send me news automatically. Probly make a Youtube video.


* TODO Scheduled Blocks project rewrite in Haskell

Schedule blocks is a project written in python. It is used to calculate the slot leader (blocks) of the Cardano blockchain given a VRF key of the pool. I'm learning Haskell so this is a good practice with features like API calls and using dynamic library.


** Update <2022-02-07 Mon>

I have the informations ready. Learning how to call the =libsodium= library to help with cryptography functions.


* DONE Rewrite my website to include my org files
SCHEDULED: <2022-01-30 Sun>

May be a rework. Replace nuxt with vite.

** Update <2022-02-07 Mon>

I replace it with Hugo and Org file export. Had a great time learning both.


* DONE Learn magit [3/3]
SCHEDULED: <2022-01-30 Thu>

- [X] git log-graph
- [X] git branch -b
- [X] git commit -m


* DONE Sync config files using stow [3/3]
SCHEDULED: <2022-01-27 Thu>

- [X] emacs / doom emacs
- [X] nvim
- [X] zshrc

Note:
- For ~zshrc~ I decided to have only the alias synced up. Each machine should have it's own
  zshrc
