#+hugo_base_dir: ~/Documents/chop-ink/

#+TITLE: My TODO List
#+AUTHOR: Chop Tr (trchopan)
#+DESCRIPTION: I should keep this short and clean it often

* WORK

** Healthcare Liff
SCHEDULED: <2022-02-07 Mon>

- Remove the hospital search components
- Add the new question 2 flow


** Cardano Commands path to Metadata Json file bug
SCHEDULED: <2022-02-12 Sat>

*** TODO Correct chdir for all commands

~cardano-commands~ should able to find pool-metadata json. Currently it looks into the ~cold-keys~ folder.

<2022-02-07 Mon>

Looks like I have to do a lot of rewrite to stream like the steps. Currently TK (pool owner) and me (pool operator) has to do a lot of manual work of remember steps.

Choosing to have a step-by-step command line interface using Typescript + [[https://github.com/SBoudrias/Inquirer.js][Inquirer]] library.


** Move my new configs and setup from PERSONAL to WORK
SCHEDULED: <2022-01-31 Mon>

* PERSONAL

** TODO Scheduled Blocks project rewrite in Haskell
SCHEDULED: <2022-01-30 Sun> DEADLINE: <2022-02-05 Sat>

Schedule blocks is a project written in python. It is used to calculate the slot leader (blocks) of the Cardano blockchain given a VRF key of the pool. I'm learning Haskell so this is a good practice with features like API calls and using dynamic library.


*** <2022-02-07 Mon>

I have the informations ready. Learning how to call the =libsodium= library to help with cryptography functions.


** DONE Rewrite my website to include my org files
SCHEDULED: <2022-01-30 Sun>

May be a rework. Replace nuxt with vite.

*** Update <2022-02-07 Mon>

I replace it with Hugo and Org file export. Had a great time learning both.


** DONE Learn magit [3/3]
SCHEDULED: <2022-01-30 Thu>

- [X] git log-graph
- [X] git branch -b
- [X] git commit -m


** DONE Sync config files using stow [3/3]
SCHEDULED: <2022-01-27 Thu>

- [X] emacs / doom emacs
- [X] nvim
- [X] zshrc

Note:
- For ~zshrc~ I decided to have only the alias synced up. Each machine should have it's own
  zshrc
